---
title: "About Replication Pilot Analysis Code"
output: html_document
date: '2022-06-09'
---

# About this code

## Motivation
This sub-routine was used to analyse pilot survey responses for a Discrete Choice Experiment study that is currently being written up. Future versions of this program will include details of the parent study.

## Status
This code has been minimally adapted from when it was first applied. It has not been formatted for consistency or ease of use and a number of sections have copied almost unchanged from online examples provided by other authors to demonstrate the third party functions (in particular from the idefix package) used in this program. Future releases of this program aim to adopt a more consistent and integrated approach that should make the program easier to follow and adapt.

## Use
When using this code it is important to note that some of the steps in this program involve interactivity - they generate a prompt that a user must respond to before proceeding. Therefore, **this code should be run step by step** (i.e run one chunk at a time and do not try to run the program by knitting the R Markdown version of this code). Although it would be possible to add work-arounds to the interactivity issue, running the program by knitting the RMD version is still not recommended as it will prevent the documents generated by this program from rendering properly. 
