---
title: "About Replication Pilot Design Code"
output: html_document
date: '2022-06-09'
---

# About this code

## Motivation
This program can be used to generate pilot survey efficient design and choice cards for studies to replicate a Discrete Choice Experiment study that is currently being written up. Future versions of this program will include details of the parent study.

## Status
This code has been adapted from the code originally used in the study to make it easier to generalise. If you have access to the study dataset, this code will still generate an identical pilot design to that used in our study. Future releases of this program will include synthetic data to allow those without access to the study dataset to run it from start to finish. The replication code will produce an efficient design with different choice sets to that produced in the original study.

## Use
When using this code it is important to note that some of the steps in this program involve interactivity - they generate a prompt that a user must respond to before proceeding. Therefore, **this code should be run step by step** (i.e run one chunk at a time and do not try to run the program by knitting the R Markdown version of this code). Although it would be possible to add work-arounds to the interactivity issue, running the program by knitting the RMD version is still not recommended as it will prevent the documents generated by this program from rendering properly. 
