---
title: "About Complete Survey Design Program Code"
output: html_document
date: '2022-06-09'
---

# About this code

## Motivation
This program was used to develop a pilot survey design, analyse pilot survey responses and generate a final survey choice efficient design and choice cards for for a Discrete Choice Experiment study that is currently being written up. Future versions of this program will include details of the parent study.

## Status
This code has been adapted from the code originally used in the study to make it easier to generalise. If you have access to the study dataset, this code will still generate an identical design to that used in our study. Future releases of this program will include synthetic data to allow those without access to the study dataset to run it from start to finish. The replication code will produce an efficient design with different choice sets to that produced in the original study.

## Use
Note, for reporting purposes this program can be executed in full so long as you have access to the external datasets referenced in the code. These datasets will only be available on completion of a study. When using the program to help design the study it is necessary to only execute the first part (design of pilot study), then collect pilot data, before returning to execute the remaining parts of the program. It should also be noted that some of the steps in this program involve interactivity - they generate a prompt that a user must respond to before proceeding. Therefore, **this code should be run step by step** (i.e run one chunk at a time and do not try to run the program by knitting the R Markdown version of this code). Although it would be possible to add work-arounds to the interactivity issue, running the program by knitting the RMD version is still not recommended as it will prevent the documents generated by this program from rendering properly. 
