---
title: "XX_Funs"
output: html_document
date: '2022-06-08'
---

```{r}
launch_survey_preview <- function(dce_design_ls,
                                  block_1L_int = integer(0),
                                  button_txt_1L_chr = character(0),
                                  end_txt_1L_chr = character(0),
                                  intro_text_1L_chr = character(0),
                                  set_idx_1L_int = 1L,
                                  transform_att_nms_1L_lgl = T){
  atts_chr <- get_atts(dce_design_ls$choice_sets_ls$att_lvls_tb, return_1L_chr = "all")
  if(transform_att_nms_1L_lgl)
    atts_chr <- atts_chr %>% stringr::str_replace_all("_"," ")
  des_mat <- dce_design_ls$efnt_dsn_ls[[set_idx_1L_int]]$design
  if(!identical(block_1L_int, integer(0))){
    intro_sfx_1L_chr <- paste0("(Choice cards from  block ", block_1L_int,")")
    indcs_int <- dce_design_ls$choice_cards_ls[[set_idx_1L_int]]$block_idxs_ls[[block_1L_int]]
    des_mat <- des_mat[cut(1:nrow(des_mat),
                           dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int, labels=F) %in% indcs_int ,]
    total_1L_int <- dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int / dce_design_ls$choice_sets_ls$nbr_of_blocks_1L_int
  }else{
    intro_sfx_1L_chr <- "(All choice cards from all blocks)"
    total_1L_int <- dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int
  }
  if(identical(intro_text_1L_chr, character(0)))
    intro_text_1L_chr <- paste0("Survey Preview ",intro_sfx_1L_chr)
  if(identical(button_txt_1L_chr, character(0)))
    button_txt_1L_chr = "Please choose the alternative you prefer"
  if(identical(end_txt_1L_chr, character(0)))
    end_txt_1L_chr <- "Thanks for taking the survey"
  idefix::SurveyApp(des = des_mat,
                    n.total = total_1L_int,
                    alts = dce_design_ls$choice_sets_ls$alternatives_chr,
                    atts = atts_chr,
                    lvl.names = make_tfd_lvls_ls(dce_design_ls) %>% unname(),
                    c.lvls = get_lvls(dce_design_ls$choice_sets_ls$att_lvls_tb, return_1L_chr = "cont") %>% unname() %>% purrr::map(~as.numeric(.x)),
                    coding = get_att_smrys(dce_design_ls,return_1L_chr = "type"),
                    buttons.text = button_txt_1L_chr,
                    intro.text = intro_text_1L_chr,
                    end.text = end_txt_1L_chr,
                    no.choice = dce_design_ls$choice_sets_ls$opt_out_idx_1L_int,
                    alt.cte = dce_design_ls$priors_ls[[min(set_idx_1L_int,length(dce_design_ls$priors_ls))]]$altv_con_int)

}
```


```{r}
make_pilot_analysis_ls <- function(pilot_ds_tb,
                                   dce_design_ls,
                                   constraints_ls = list(),
                                   choice_var_pfx_1L_chr = "DCE_B",
                                   draws_1L_int = 100L,
                                   seed_1L_int = 1987,
                                   set_idx_1L_int = 1L){
  set.seed(seed_1L_int)
  pilot_ds_tb <- pilot_ds_tb %>% 
  make_choice_responses_ds(choice_vars_pfx_1L_chr = choice_var_pfx_1L_chr)
  case_choices_mat <- make_case_choices_mat(pilot_ds_tb,
                                            block_idxs_ls = dce_design_ls$choice_cards_ls[[set_idx_1L_int]]$block_idxs_ls,
                                            choice_sets_ls = dce_design_ls$choice_sets_ls,
                                            design_mat = dce_design_ls$efnt_dsn_ls[[set_idx_1L_int]]$design,
                                            choice_vars_pfx_1L_chr = choice_var_pfx_1L_chr)
  choice_int <- make_choice_int(pilot_ds_tb,
                                choice_sets_ls = dce_design_ls$choice_sets_ls,
                                choice_vars_pfx_1L_chr = choice_var_pfx_1L_chr)
  var_nms_chr <- make_case_choices_ds(case_choices_mat,
                                      choice_sets_ls = dce_design_ls$choice_sets_ls) %>%
    names()
  high_bounds_dbl <- rep(Inf, length(var_nms_chr))
  low_bounds_dbl <-- high_bounds_dbl
  low_bounds_dbl <- var_nms_chr %>%
    purrr::map2_dbl(low_bounds_dbl,
                    ~ifelse(.x %in% names(constraints_ls),
                            constraints_ls[[.x]][1],
                            .y))
  high_bounds_dbl <- var_nms_chr %>%
    purrr::map2_dbl(high_bounds_dbl,
                    ~ifelse(.x %in% names(constraints_ls),
                            constraints_ls[[.x]][2],
                            .y))
  pilot_analysis_ls <- idefix::ImpsampMNL(n.draws = draws_1L_int, 
                                          prior.mean = dce_design_ls$priors_ls[[set_idx_1L_int]]$priors_dbl, 
                                          prior.covar = diag(length(dce_design_ls$priors_ls[[set_idx_1L_int]]$priors_dbl)), 
                                          des = case_choices_mat, 
                                          n.alts = length(dce_design_ls$choice_sets_ls$alternatives_chr), 
                                          y = choice_int, 
                                          lower = low_bounds_dbl, 
                                          upper = high_bounds_dbl, 
                                          alt.cte = dce_design_ls$priors_ls[[set_idx_1L_int]]$altv_con_int)
  return(pilot_analysis_ls)
}
```
```{r echo=TRUE}
make_choice_cards <- function(dce_design_ls,
                              block_idxs_ls = list(),
                              seed_1L_int = 1987,
                              set_idx_1L_int = 1L,
                              transform_att_nms_1L_lgl = T){
  set.seed(seed_1L_int)
  survey_ls <- idefix::Decode(des = dce_design_ls$efnt_dsn_ls[[set_idx_1L_int]]$design,
                              lvl.names = make_tfd_lvls_ls(dce_design_ls),
                              coding = get_att_smrys(dce_design_ls,return_1L_chr = "type"),
                              c.lvls = get_lvls(dce_design_ls$choice_sets_ls$att_lvls_tb, return_1L_chr = "cont") %>%
                                unname() %>%
                                purrr::map(~as.numeric(.x)),
                              alt.cte = dce_design_ls$priors_ls[[min(set_idx_1L_int,length(dce_design_ls$priors_ls))]]$altv_con_int,
                              n.alts = length(dce_design_ls$choice_sets_ls$alternatives_chr),
                              no.choice = dce_design_ls$choice_sets_ls$opt_out_idx_1L_int)
  attributes_chr <- dce_design_ls$choice_sets_ls$att_lvls_tb$attribute_chr %>% unique()
  if(transform_att_nms_1L_lgl){
    attributes_chr <- stringr::str_replace_all(attributes_chr,"_"," ")
  }
  choices_tb <- tibble::as_tibble(survey_ls$design,
                                  rownames = "Choice")
  colnames(choices_tb) <- c("Choice", attributes_chr)
  choices_tb <- choices_tb %>%
    dplyr::filter(!startsWith(Choice, "no"))
  if(identical(block_idxs_ls,list())){
    indices_int <- 1:dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int
    folds_int <- cut(indices_int,
                     breaks = dce_design_ls$choice_sets_ls$nbr_of_blocks_1L_int,
                     labels = FALSE) %>% sample()
    block_idxs_ls <- 1:dce_design_ls$choice_sets_ls$nbr_of_blocks_1L_int %>%
      purrr::map(~indices_int[folds_int==.x])
  }
  choice_cards_tb_ls <- purrr::map(block_idxs_ls,
                                   ~ make_choice_cards_tb_ls(.x,choices_tb))
  choice_cards_html_ls <- purrr::map(choice_cards_tb_ls,
                                     ~ make_cards_html_ls(.x))
  choice_cards_ls <- list(survey_ls = survey_ls,
                          block_idxs_ls = block_idxs_ls,
                          choices_tb = choices_tb,
                          choice_cards_tb_ls = choice_cards_tb_ls,
                          choice_cards_html_ls = choice_cards_html_ls)
  return(choice_cards_ls)

}
```
```{r echo=FALSE}
make_choice_int <- function(ds_tb,
                            choice_sets_ls,
                            choice_vars_pfx_1L_chr ="DCE_B"){
  choice_int <- purrr::map(1:nrow(ds_tb),
                           ~ make_choice_responses_ds(ds_tb,
                                                      choice_vars_pfx_1L_chr = choice_vars_pfx_1L_chr) %>%
                             dplyr::slice(.x) %>%
                             as.numeric() %>%
                             purrr::map(
                               ~ if(is.na(.x)){
                                 NULL
                               }else{
                                 choice_idcs_int <- rep(0,length(choice_sets_ls$alternatives_chr))
                                 choice_idcs_int[.x] <- 1
                                 choice_idcs_int
                               }) %>%
                             unlist()) %>%
    unlist()
  return(choice_int)
}
```

```{r echo = FALSE}
make_efnt_dsn_mat <- function(dce_design_ls,
                              parallel_1L_lgl = FALSE,
                              pilot_analysis_ls = list(),
                              priors_idx_1L_int = 1L,
                              set_idx_1L_int = 1L,
                              start_dsn_mat_ls = NULL){
  efnt_dsn_mat <- idefix::Modfed(cand.set = dce_design_ls$cndt_design_mat,
                                 n.sets = dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int,
                                 n.alts = length(dce_design_ls$choice_sets_ls$alternatives_chr),
                                 no.choice = dce_design_ls$choice_sets_ls$opt_out_1L_lgl,
                                 alt.cte = dce_design_ls$priors_ls[[priors_idx_1L_int]]$altv_con_int,
                                 parallel = parallel_1L_lgl,
                                 par.draws = {if(identical(pilot_analysis_ls,list())){dce_design_ls$priors_ls[[priors_idx_1L_int]]$params_xx}else{pilot_analysis_ls[[set_idx_1L_int]]$sample}},
                                 start.des = start_dsn_mat_ls)
  return(efnt_dsn_mat)
}
```

```{r echo=FALSE}
add_design_spec <- function(dce_design_ls = list(),
                            add_cndt_design_mat = F,
                            alternatives_chr = character(0),
                            att_lvls_tb = tibble::tibble(),
                            #block_idcs_1L_int = integer(0),
                            block_idxs_ls = list(),
                            choice_var_pfx_1L_chr = "DCE_B",
                            constraints_ls = list(),
                            cost_att_idx_1L_int = integer(0),
                            cost_pfx_1L_chr = "",
                            cost_sfx_1L_chr = "",
                            design_mat = matrix(numeric(0)),
                            draws_1L_int = 10L,
                            nbr_of_blocks_1L_int = integer(0),
                            nbr_of_sets_1L_int = integer(0),
                            opt_out_idx_1L_int = integer(0),
                            parallel_1L_lgl = FALSE,
                            #pilot_analysis_ls = NULL,
                            pilot_ds_tb = NULL,
                            priors_dbl = numeric(0),
                            priors_idx_1L_int = integer(0),
                            seed_1L_int = 1987,
                            set_idx_1L_int = integer(0),
                            #start_dsn_mat = NULL,
                            transform_att_nms_1L_lgl = T){
  if(is.null(dce_design_ls$choice_cards_ls)){
    dce_design_ls$choice_cards_ls <- list()
  }
  if(is.null(dce_design_ls$choice_sets_ls)){
    dce_design_ls$choice_sets_ls <- list(alternatives_chr = alternatives_chr,
                                         att_lvls_tb = att_lvls_tb,
                                         nbr_of_blocks_1L_int = nbr_of_blocks_1L_int,
                                         nbr_of_sets_1L_int = nbr_of_sets_1L_int,
                                         opt_out_1L_lgl = logical(0),
                                         opt_out_idx_1L_int = integer(0))
  }
  if(!identical(alternatives_chr,character(0))){
    dce_design_ls$choice_sets_ls$alternatives_chr <- alternatives_chr
  }
  if(!identical(att_lvls_tb, tibble::tibble())){
    dce_design_ls$choice_sets_ls$att_lvls_tb <- att_lvls_tb
  }
  if(!identical(design_mat, matrix(numeric(0)))){
    dce_design_ls$design_mat <- design_mat
  }
  if(!identical(nbr_of_sets_1L_int, integer(0))){
    dce_design_ls$choice_sets_ls$nbr_of_sets_1L_int <- nbr_of_sets_1L_int
  }
  if(!identical(nbr_of_blocks_1L_int, integer(0))){
    dce_design_ls$choice_sets_ls$nbr_of_blocks_1L_int <- nbr_of_blocks_1L_int
  }
  if(!identical(opt_out_idx_1L_int,integer(0))){
    dce_design_ls$choice_sets_ls$opt_out_idx_1L_int <- opt_out_idx_1L_int ###
  }
  if(!identical(opt_out_idx_1L_int,integer(0))){
    dce_design_ls$choice_sets_ls$opt_out_1L_lgl <- ifelse(is.na(dce_design_ls$choice_sets_ls$opt_out_idx_1L_int),
                                                          F,
                                                          T)
  }
  if(add_cndt_design_mat){
    dce_design_ls$cndt_design_mat <- idefix::Profiles(lvls = get_att_smrys(dce_design_ls),
                                                      coding = get_att_smrys(dce_design_ls,return_1L_chr = "type"),
                                                      c.lvls = get_lvls(dce_design_ls$choice_sets_ls$att_lvls_tb, return_1L_chr = "cont") %>% unname() %>% purrr::map(~as.numeric(.x)))
  }else{
    if(is.null(dce_design_ls$cndt_design_mat)){
      dce_design_ls$cndt_design_mat <- matrix(numeric(0))
    }
  }
  if(is.null(dce_design_ls$cost_att_idx_1L_int) | !identical(cost_att_idx_1L_int, integer(0))){
    dce_design_ls$cost_att_idx_1L_int <- cost_att_idx_1L_int
  }
  if(is.null(dce_design_ls$cost_pfx_1L_chr) | !identical(cost_pfx_1L_chr, "")){
    dce_design_ls$cost_pfx_1L_chr <- cost_pfx_1L_chr
  }
  if(is.null(dce_design_ls$cost_sfx_1L_chr) | !identical(cost_sfx_1L_chr, "")){
    dce_design_ls$cost_sfx_1L_chr <- cost_sfx_1L_chr
  }
  if(is.null(dce_design_ls$design_mat) | !identical(design_mat,matrix(numeric(0)))){
    dce_design_ls$design_mat <- design_mat
  }
  if(is.null(dce_design_ls$efnt_dsn_ls)){
    dce_design_ls$efnt_dsn_ls <- list()
  }
  if(is.null(dce_design_ls$pilot_analysis_ls)){
    dce_design_ls$pilot_analysis_ls <- list()
  }
  if(is.null(dce_design_ls$priors_ls)){
    dce_design_ls$priors_ls <- list()
  }
  if(!identical(priors_dbl, numeric(0))){
    dce_design_ls$priors_ls <- append(dce_design_ls$priors_ls,
                                      list(make_priors_ls(dce_design_ls,
                                                          priors_dbl = priors_dbl,
                                                          draws_1L_int = draws_1L_int,  seed_1L_int = seed_1L_int)) %>%
                                        stats::setNames(paste0("Set_",
                                                               length(dce_design_ls$priors_ls) + 1)))
  }
  if(!identical(priors_idx_1L_int, integer(0))){
    if(identical(dce_design_ls$pilot_analysis_ls,list())){
      start_dsn_mat_ls <- NULL
    }else{
      start_dsn_mat_ls <- list(dce_design_ls$efnt_dsn_ls[[set_idx_1L_int]]$design)
    }
    dce_design_ls$efnt_dsn_ls <- append(dce_design_ls$efnt_dsn_ls,
                                        list(make_efnt_dsn_mat(dce_design_ls,
                                                               parallel_1L_lgl = parallel_1L_lgl,
                                                               pilot_analysis_ls = {if(identical(dce_design_ls$pilot_analysis_ls,list())){
                                                                 NULL
                                                                 }else{dce_design_ls$pilot_analysis_ls}},
                                                               priors_idx_1L_int = priors_idx_1L_int,
                                                               set_idx_1L_int = set_idx_1L_int,
                                                               start_dsn_mat_ls = start_dsn_mat_ls)) %>%
                                          stats::setNames(paste0("Set_", length(dce_design_ls$efnt_dsn_ls) + 1)))
  }
  if(!identical(set_idx_1L_int, integer(0))){
    dce_design_ls$choice_cards_ls <- append(dce_design_ls$choice_cards_ls,
                                            list(make_choice_cards(dce_design_ls,
                                                                   block_idxs_ls = block_idxs_ls,
                                                                   seed_1L_int = seed_1L_int,
                                                                   set_idx_1L_int = set_idx_1L_int,
                                                                   transform_att_nms_1L_lgl = transform_att_nms_1L_lgl)) %>%
                                              stats::setNames(paste0("Set_", length(dce_design_ls$choice_cards_ls) + 1)))

  }
  if(!is.null(pilot_ds_tb)){
    dce_design_ls$pilot_analysis_ls <- append(dce_design_ls$pilot_analysis_ls,
                                      list(make_pilot_analysis_ls(pilot_ds_tb,
                                                                  dce_design_ls = dce_design_ls,
                                                                  constraints_ls = constraints_ls,
                                                                  choice_var_pfx_1L_chr = choice_var_pfx_1L_chr,
                                                                  draws_1L_int = draws_1L_int,
                                                                  seed_1L_int = seed_1L_int,
                                                                  set_idx_1L_int = set_idx_1L_int)) %>%
                                        stats::setNames(paste0("Set_", length(dce_design_ls$pilot_analysis_ls) + 1)))
  }
  return(dce_design_ls)
}
```
```{r}

```
```{r}

```
```{r}

```

```{r}

```

```{r}

```

